# Generated by Django 2.2.7 on 2019-11-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(default='', max_length=50, verbose_name='First')),
                ('last_name', models.CharField(default='', max_length=50, verbose_name='Last')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
