# Generated by Django 2.2.7 on 2019-11-25 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_homesignup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeSignup',
        ),
    ]
