# Generated by Django 2.2.5 on 2019-11-13 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoOfTheDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('photographer', models.CharField(default='', max_length=100)),
                ('img', models.ImageField(default='potd_default.jpg', upload_to='potd')),
                ('photographer_url', models.URLField(default='', max_length=100, verbose_name='Photographer url')),
                ('slug', models.SlugField(default='', unique=True)),
                ('draft', models.BooleanField(default=False)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Photo of the day',
            },
        ),
    ]
