# Generated by Django 2.2.5 on 2019-11-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photooftheday',
            name='slug',
            field=models.SlugField(default='', max_length=140, unique=True),
        ),
    ]
