# Generated by Django 2.2.5 on 2019-11-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potd', '0002_auto_20191113_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photooftheday',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
