# Generated by Django 2.2.5 on 2019-11-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potd', '0005_auto_20191114_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='photooftheday',
            name='featured_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
