# Generated by Django 2.2.6 on 2019-11-05 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20191105_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='background',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='post',
            name='backgrounds',
        ),
        migrations.AddField(
            model_name='post',
            name='backgrounds',
            field=models.ManyToManyField(through='quotes.PostBackground', to='quotes.Background'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(through='quotes.PostCategory', to='quotes.Category'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Category'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Post'),
        ),
        migrations.AddField(
            model_name='postbackground',
            name='background',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Background'),
        ),
        migrations.AddField(
            model_name='postbackground',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Post'),
        ),
    ]
