# Generated by Django 2.2.6 on 2019-11-05 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_auto_20191105_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name_plural': 'post_categories'},
        ),
    ]
