# Generated by Django 2.2.6 on 2019-11-05 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_auto_20191105_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name_plural': 'postcategories'},
        ),
    ]
