# Generated by Django 2.2.6 on 2019-11-06 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_auto_20191105_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name_plural': 'post categories'},
        ),
    ]
