# Generated by Django 2.2.6 on 2019-11-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_auto_20191108_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feature',
            field=models.BooleanField(default=False),
        ),
    ]
