# Generated by Django 2.2.5 on 2019-11-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0015_auto_20191113_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='feature',
            new_name='home_feature',
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='img_author',
            field=models.CharField(default='', max_length=50, verbose_name='Photographer'),
        ),
        migrations.AddField(
            model_name='post',
            name='img_author_url',
            field=models.URLField(default='', max_length=100, verbose_name='Photographer url'),
        ),
    ]
