# Generated by Django 2.2.5 on 2019-11-13 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0016_auto_20191113_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='home_feature',
            new_name='feature',
        ),
    ]
