# Generated by Django 2.2.5 on 2019-11-13 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0021_potd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='POTD',
        ),
    ]
