# Generated by Django 2.2.5 on 2019-11-15 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0022_delete_potd'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteCollections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('img', models.ImageField(default='default.jpg', upload_to='quote_pics', verbose_name='Collection BG Img')),
                ('draft', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Quote Collections',
            },
        ),
    ]
