# Generated by Django 2.2.5 on 2019-11-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0023_quotecollections'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='been_featured',
            field=models.BooleanField(default=False, verbose_name='Has Been QOTD Before'),
        ),
    ]
