# Generated by Django 2.2.5 on 2019-11-15 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0024_post_been_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='been_featured',
            new_name='featured_as_qotd',
        ),
    ]
