# Generated by Django 2.2.5 on 2019-11-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0027_auto_20191114_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotecollections',
            name='quote',
            field=models.ManyToManyField(to='quotes.Post'),
        ),
    ]
