# Generated by Django 2.2.5 on 2019-11-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0029_auto_20191122_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feature_qotd',
            field=models.BooleanField(default=False, verbose_name='Featured QOTD'),
        ),
    ]
