# Generated by Django 2.2.5 on 2019-11-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0030_auto_20191122_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
